version: "3.7"
services:
  speedlogger-web:
    image: brennentsmith/internet-speed-logger
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./config:/data/config
  speedlogger-runner:
    image: brennentsmith/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
    volumes:
      - ./config:/data/config
  mongo:
    image: webhippie/mongodb:latest-arm32v7
    expose:
      - "27017"
    environment:
      - MONGODB_USERNAME=speedtest
      - MONGODB_PASSWORD=speedtest
      - MONGODB_DATABASE=speedtest
    volumes:
      - ./mongo-persistence:/var/lib/mongodb
